### PR TITLE
Fix issue with AstSelPlus

### LINKED ISSUE #156: ibex_simple_system: ram_2p.sv  doesn't work in verilator
Parsing ``ram_2p.sv`` (with ``prim_generic_ram_2p.sv`` and ``prim_ram_2p.sv``) file using UHDM frontend in verilator results in:
```
%Error-UNSUPPORTED: Unsupported: Slice of non-constant bounds
                            : ... In instance ibex_simple_system.u_ram.u_ram..u_impl_generic
%Error: Internal Error: ../V3Width.cpp:1015: AstSelPlus should disappear after widthSel
                                : ... In instance ibex_simple_system.u_ram.u_ram..u_impl_generic
                        ... See the manual and https://verilator.org for more assistance.
```

### PR DESCRIPTION
**Pull request by wtatarski**
Fixes https://github.com/alainmarcel/uhdm-integration/issues/156

### CODE REVIEW

File: src/UhdmAst.cpp [hunk 1]
```diff
@@ -2209,11 +2211,28 @@ namespace UhdmAst {
...
+	      std::cout << "AstSelPlus2\n";
+              //select = new AstSelPlus(new FileLine("uhdm"), fromp, bitp, nullptr);
+              select = new AstSelBit(new FileLine("uhdm"), fromp, bitp);
+		select->dumpTree(cout, "select");
+		fromp->dumpTree(cout, "fromp");
+		bitp->dumpTree(cout, "bitp");
+            } else if (item->type() == AstType::atSelPlus) {
+	      std::cout << "AstSelBit3\n";
+		select->dumpTree(cout, "select");
+                select = new AstSelPlus(new FileLine("uhdm"), fromp, bitp->op2p(), bitp->op3p());
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: I am not sure if I read the code correctly, but could we do sth like the following?
```
AstSelPlus* selplusp = VN_CAST(item, SelPlus);
select = new AstSelPlus(new FileLine("uhdm"), fromp, selplusp->bitp(), selplusp->widthp());
```

This way we avoid using `op`s directly

Comment (tgorochowik) [reply src/UhdmAst.cpp]: Or maybe we could even avoid generating the internal `AstSelPlus` node if we don't use it anyway? Or is it needed in some other cases?

Comment (tgorochowik) [reply src/UhdmAst.cpp]: Now that I think about it, maybe we don't even need to create new nodes here.
We could probably just do sth like:
```
AstSelPlus* selplusp = VN_CAST(item, SelPlus);
selplusp->fromp(fromp);
select = selplusp;
```
???

**Comment by rkapuscik** [comment]
Regarding module tests in CI - they're using synthesis target for now. I don't think the ram_2p module added in https://github.com/alainmarcel/uhdm-integration/pull/201 is used there, so you'll have to change [main.yml](https://github.com/antmicro/verilator/blob/uhdm-verilator/.github/workflows/main.yml) for the test to work.

File: src/UhdmAst.cpp [hunk 2]
```diff
@@ -2209,6 +2209,14 @@ namespace UhdmAst {
                   fromp,
                   ((AstSelExtract*)item)->msbp()->cloneTree(true),
                   ((AstSelExtract*)item)->lsbp()->cloneTree(true));
+            } else if(item->type() == AstType::en::atConst) {
+              select = new AstSelBit(new FileLine("uhdm"), fromp, bitp);
+            } else if (item->type() == AstType::atSelPlus) {
```
Comment (rkapuscik) [inline src/UhdmAst.cpp:2214]: Can we handle `-:` selection here as well? Only the node type would change.

**Review by rkapuscik — CHANGES_REQUESTED** [review]

File: src/UhdmAst.cpp (hunk 1 above)
Comment (wtatarski) [reply src/UhdmAst.cpp]: It looks like your first suggestion works well. I'd stick to it.

File: src/UhdmAst.cpp (hunk 2 above)
Comment (wtatarski) [reply src/UhdmAst.cpp:2214]: Added `SelMinus`

File: src/UhdmAst.cpp [hunk 3]
```diff
@@ -2209,6 +2209,21 @@ namespace UhdmAst {
...
+              AstSelPlus* selplusp = VN_CAST(item, SelPlus);
+              select = new AstSelPlus(new FileLine("uhdm"),
+                  fromp,
+                  selplusp->bitp(),
+                  selplusp->widthp());
+            } else if (item->type() == AstType::atSelMinus) {
+              AstSelMinus* selplusp = VN_CAST(item, SelMinus);
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: `selminusp` (variable name)

**Review by tgorochowik — APPROVED** [review]
LGTM

**Review by rkapuscik — APPROVED** [review]
