### PR TITLE
Test simulator_ctrl and ibex_register_file_latch

### LINKED ISSUE #152: ibex-simple-system: ibex_register_file_latch.sv doesn't work in verilator
Parsing ``ibex_register_file_latch.sv`` file using UHDM frontend in verilator results in ``%Error: Exiting due to 1 error(s)`` (without any more message), running with ``--debug`` flag says:
```
%Error: Exiting due to 1 error(s)                                                                        
- V3Ast.cpp:1120:     Dumping ./Vibex_simple_system_990_final.tree                                                                                                                                                 
%Error: Internal Error: ../V3Broken.cpp:253: Broken link in node->dtypep() to 0x5555578f12f0
-node: VAR (AEEB) <e51363> {d0aa} @dt=(BEEB)@(nw1)  file INPUT PORT
%Error: Internal Error: Aborting since under --debug 
```

### LINKED ISSUE #154: ibex-simple-system: simulator_ctrl.sv  doesn't work in verilator
Parsing ``simulator_ctrl.sv`` file using UHDM frontend in verilator results in:
```
%Error: Missing arguments for $display-like format
%Error: Exiting due to 1 error(s)
```

### PR DESCRIPTION
**Pull request by rkapuscik**
Remove simulator_ctrl and ibex_register_file_latch from the skip list and parse them using UHDM.
Fixes https://github.com/alainmarcel/uhdm-integration/issues/154.
Fixes https://github.com/alainmarcel/uhdm-integration/issues/152.

### CODE REVIEW

File: src/UhdmAst.cpp [hunk 1]
```diff
@@ -2538,9 +2538,28 @@ namespace UhdmAst {
...
+                                nullptr,
+                                args);
+          auto* stop = new AstStop(new FileLine("uhdm"), true);
+          node->addNext(stop);
+          return node;
+        } else if (objectName == "$fatal") {
+          node = new AstDisplay(new FileLine("uhdm"),
+                                AstDisplayType::DT_FATAL,
+                                nullptr,
+                                nullptr);
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: A couple of questions:
* Why do we not handle arguments when calling `$fatal`?
* Shouldn't that code be common with `$error`?
* Adding `$warning` and `$info` seems to be trivial here, could we add that too?
* ~~Does verilator generate the implicit `$finish` when `$fatal` is called? If not, shouldn't we generate a node for that too and add it to the statement list here explicitly?~~ (just noticed the explicit `stop` node, that should do)

Comment (rkapuscik) [reply src/UhdmAst.cpp]: I missed one case in grammar where `$fatal` arguments were used, now this is corrected and all four calls (`$info`, `$warning`, `$error`, `$fatal`) use common handling.

**Review by tgorochowik — APPROVED** [review]

File: src/UhdmAst.cpp [hunk 2]
```diff
@@ -968,19 +968,10 @@ namespace UhdmAst {
...
-                                                     nullptr,
-                                                     nullptr);
-              if (objectType == vpiContAssign)
-                assign = new AstAssignW(new FileLine("uhdm"), var_ref, rvalue);
-              else
-                assign = new AstAssign(new FileLine("uhdm"), var_ref, rvalue);
-              var->addNextNull(assign);
+              // This is not a true assignment
+              // Set initial value to a variable and return it
+              AstVar* var = static_cast<AstVar*>(lvalue);
```
Comment (tgorochowik) [inline src/UhdmAst.cpp:973]: I see that we already use regular casting throughout this file so I guess it is okay to keep it here too (at least it is consistent), but in general, Verilator uses the `VN_CAST` macro to check and cast and the `VN_IS` macro to just check the type of the node.
At some point we will probably have to convert that to use the macros if we wish to be integrated with mainline Verilator
(this is low prio of course)

Comment (tgorochowik) [reply src/UhdmAst.cpp:973]: In addition, the general convention in verilator is to add `p` prefix if the variable is a pointer, so
`AstVar var;` would be ok, but for a pointer it should be `AstVar* varp;`
(This is also something that should be done in a bulk)

Comment (rkapuscik) [reply src/UhdmAst.cpp:973]: Created https://github.com/antmicro/verilator/issues/35 for this task.
