### PR TITLE
Test ibex_core_tracing

### LINKED ISSUE #150: ibex-simple-system: ibex_core_tracing.sv  doesn't work in verilator
Parsing ``ibex_core_tracing.sv``  file using UHDM frontend in verilator results in ``Verilator internal fault, sorry``, gdb bt:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555556088696 in vpi_handle ()
#0  0x0000555556088696 in vpi_handle ()
#1  0x0000555555bbfd10 in UhdmAst::getDType (obj_h=0x555556e1e6a0, visited=..., top_nodes=0x7fffffff9f60) at ../UhdmAst.cpp:264
#2  0x0000555555bc4bff in UhdmAst::visit_object (obj_h=0x555556e1e6a0, visited=..., top_nodes=0x7fffffff9f60) at ../UhdmAst.cpp:634
#3  0x0000555555bbdfa9 in UhdmAst::visit_one_to_many(std::vector<int, std::allocator<int> >, unsigned int*, std::set<UHDM::BaseClass const*, std::less<UHDM::BaseClass const*>, std::allocator<UHDM::BaseClass const*> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, AstNodeModule*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, AstNodeModule*> > >*, std::function<void (AstNode*)> const&) (childrenNodeTypes=..., parentHandle=0x5555582fe8b0, visited=..., top_nodes=0x7fffffff9f60, f=...) at ../UhdmAst.cpp:32
#4  0x0000555555bc5a1c in UhdmAst::visit_object (obj_h=0x5555582fe8b0, visited=..., top_nodes=0x7fffffff9f60) at ../UhdmAst.cpp:793
#5  0x0000555555bbdfa9 in UhdmAst::visit_one_to_many(std::vector<int, std::allocator<int> >, unsigned int*, std::set<UHDM::BaseClass const*, std::less<UHDM::BaseClass const*>, std::allocator<UHDM::BaseClass const*> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, AstNodeModule*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, AstNodeModule*> > >*, std::function<void (AstNode*)> const&) (childrenNodeTypes=..., parentHandle=0x55555812a920, visited=..., top_nodes=0x7fffffff9f60, f=...) at ../UhdmAst.cpp:32
#6  0x0000555555bc56e7 in UhdmAst::visit_object (obj_h=0x55555812a920, visited=..., top_nodes=0x7fffffff9f60) at ../UhdmAst.cpp:722
#7  0x0000555555bbdfa9 in UhdmAst::visit_one_to_many(std::vector<int, std::allocator<int> >, unsigned int*, std::set<UHDM::BaseClass const*, std::less<UHDM::BaseClass const*>, std::allocator<UHDM::BaseClass const*> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, AstNodeModule*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, AstNodeModule*> > >*, std::function<void (AstNode*)> const&) (childrenNodeTypes=..., parentHandle=0x555556d02f80, visited=..., top_nodes=0x7fffffff9f60, f=...) at ../UhdmAst.cpp:32
#8  0x0000555555bdf453 in UhdmAst::visit_designs (designs=..., coverage_report_stream=..., symp=0x7fffffffa1b0) at ../UhdmAst.cpp:3108
#9  0x0000555555913ab8 in V3Global::readFiles (this=0x55555669f6c0 <v3Global>) at ../V3Global.cpp:140
#10 0x0000555555754b07 in verilate (argString=...) at ../Verilator.cpp:576
#11 0x00005555557561e3 in main (argc=18, argv=0x7fffffffcf88, env=0x7fffffffd020) at ../Verilator.cpp:706
```

### PR DESCRIPTION
**Pull request by rkapuscik**
Fixes needed for simulating ibex_tracer and ibex_core_tracing via UHDM.
Fixes https://github.com/alainmarcel/uhdm-integration/issues/150.

### CODE REVIEW

File: src/UhdmAst.cpp [hunk 1]
```diff
@@ -860,12 +869,16 @@ namespace UhdmAst {
...
           // Get parameter assignments
           itr = vpi_iterate(vpiParamAssign, obj_h);
+          std::map<std::string, AstNode*> parameter_map;
           while (vpiHandle vpi_child_obj = vpi_scan(itr) ) {
             vpiHandle param_handle = vpi_handle(vpiLhs, vpi_child_obj);
             std::string param_name = vpi_get_str(vpiName, param_handle);
             sanitize_str(param_name);
             UINFO(3, "Got parameter (pin) " << param_name << std::endl);
             auto is_local = vpi_get(vpiLocalParam, param_handle);
+            std::string is_imported;
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: This name is confusing. What exactly does this represent? Is it the name of the package?

File: src/UhdmAst.cpp [hunk 2]
```diff
@@ -860,12 +869,16 @@ namespace UhdmAst {
 
           // Get parameter assignments
           itr = vpi_iterate(vpiParamAssign, obj_h);
+          std::map<std::string, AstNode*> parameter_map;
```
Comment (kbieganski) [inline src/UhdmAst.cpp]: Does this need to be a map? Seems like a set. It's fine if it's going to be used like a map in the future.

File: src/UhdmAst.cpp [hunk 3]
```diff
@@ -860,12 +869,16 @@ namespace UhdmAst {
...
           while (vpiHandle vpi_child_obj = vpi_scan(itr) ) {
             vpiHandle param_handle = vpi_handle(vpiLhs, vpi_child_obj);
             std::string param_name = vpi_get_str(vpiName, param_handle);
             sanitize_str(param_name);
             UINFO(3, "Got parameter (pin) " << param_name << std::endl);
             auto is_local = vpi_get(vpiLocalParam, param_handle);
+            std::string is_imported;
+            if (auto s = vpi_get_str(vpiImported, param_handle))
```
Comment (kbieganski) [inline src/UhdmAst.cpp]: This `if` repeats a few times in this PR. Consider making it a separate function. Also, `is_imported` sounds like a `bool`, I think it could be better named.

**Review by kbieganski — COMMENTED** [review]
Looks good, just two tiny things.

File: src/UhdmAst.cpp [hunk 4]
```diff
@@ -983,6 +1009,15 @@ namespace UhdmAst {
...
       }
       case vpiRefObj: {
+        // Recover the original package, if any
+        std::string is_imported;
+        if (auto s = vpi_get_str(vpiImported, obj_h)) {
+          is_imported = s;
+        }
+        if (is_imported != "") {
+          objectName = is_imported +"::"+ objectName;
+        }
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: Do you really need the `is_imported` variable here, two ifs and the copy of the string? Cannot this be merged into sth like:
```
        if (auto pkg_name = vpi_get_str(vpiImported, obj_h)) {
          objectName = pkg_name +"::"+ objectName;
        }
```

File: src/UhdmAst.cpp [hunk 5]
```diff
@@ -1091,6 +1127,13 @@ namespace UhdmAst {
         } else if (objectType == vpiParameter) {
           parameter_h = obj_h;
         }
+        if (auto s = vpi_get_str(vpiImported, parameter_h))
+          is_imported = s;
+        if (is_imported != "") {
+          // Skip imported parameters, they will still be visible in their packages
+          UINFO(3, "Skipping imported parameter " << objectName << std::endl);
+          return nullptr;
+        }
```
Comment (tgorochowik) [inline src/UhdmAst.cpp]: Same as above

**Review by tgorochowik — COMMENTED** [review]
LGTM in general, just some minor nitpicks

**Comment by tgorochowik** [comment]
One general comment, it looks as though the formatting is a little off. The file is consistent so that's a good thing, but it is different than the rest of Verilator. It is a good practice to keep the original formatting rules of the project when modifying it.

Reformatting should probably not be done as a part of this PR but I think it would make sense to keep the formatting the same as the rest of Verilator in general.

Verilator uses clang-format (v10 or later) with the default config so reformatting should be pretty straightforward, consider using it (but please do this separately from this PR)

File: src/UhdmAst.cpp (hunk 4 above)
Comment (tgorochowik) [reply src/UhdmAst.cpp]: @rkapuscik I am not sure what happened here. In the current version you completely removed the code that extends the object name? Was that on purpose?

Comment (rkapuscik) [reply src/UhdmAst.cpp]: Yes, when refactoring `is_imported` I noticed that the only cases when this was needed were eliminated with https://github.com/antmicro/verilator/pull/23/commits/b0ed3dbebcd456dc1abf841138f5d8ac6e0602d5, so this code was redundant.

File: src/UhdmAst.cpp (hunk 3 above)
Comment (rkapuscik) [reply src/UhdmAst.cpp]: Moved to a separate function.

File: src/UhdmAst.cpp (hunk 2 above)
Comment (rkapuscik) [reply src/UhdmAst.cpp]: It _was_ used at one point to detect whether a parameter is overridden, but their values turned out to be consistent. Changed to a set.

File: src/UhdmAst.cpp (hunk 1 above)
Comment (rkapuscik) [reply src/UhdmAst.cpp]: This reflects the way it is stored in UHDM: if there is no vpiImported node, module was not imported (and the string is empty), otherwise it contains either the name of the package the module was imported from.
I agree that this is confusing, since we do not need the name of the package at this point I changed this to a `bool` function.

File: src/UhdmAst.cpp (hunk 5 above)
Comment (rkapuscik) [reply src/UhdmAst.cpp]: Changed.

**Review by tgorochowik — APPROVED** [review]
LGTM
